In [1]:
import yfinance as yf

In [2]:
symbols = ['ACWI', 'EFA', 'EEM', '^GSPC', '^STOXX50E', '^N225', '^HSI']

In [3]:
ytd = yf.download(symbols, start='2019-12-28', end='2020-08-31', thread=True)['Adj Close']

[*********************100%***********************]  7 of 7 completed

In [4]:
ytd_ = ytd.fillna(method='ffill').iloc[2:]; ytd_

,ACWI,EEM,EFA,^GSPC,^HSI,^N225,^STOXX50E
Date,,,,,,,
2019-12-31,78.585159,44.611153,68.468071,3230.780029,28189.750000,23656.619141,3748.469971
2020-01-02,79.398285,45.515903,69.158272,3257.850098,28543.519531,23656.619141,3748.469971
2020-01-03,78.714066,44.670811,68.300446,3234.850098,28451.500000,23656.619141,3773.370117
2020-01-06,78.892563,44.561443,68.566666,3246.280029,28226.189453,23204.859375,3752.520020
2020-01-07,78.694237,44.531616,68.379326,3237.179932,28322.060547,23575.720703,3759.250000
...,...,...,...,...,...,...,...
2020-08-24,81.480003,44.770000,65.269997,3431.280029,25551.580078,22985.509766,3331.739990
2020-08-25,81.800003,45.220001,65.309998,3443.620117,25486.220703,23296.769531,3329.709961
2020-08-26,82.470001,45.340000,65.690002,3478.729980,25491.789062,23290.859375,3356.760010
2020-08-27,82.220001,44.959999,65.019997,3484.550049,25281.150391,23208.859375,3331.040039
2020-08-28,82.849998,45.549999,65.480003,3508.010010,25422.060547,22882.650391,3315.540039

In [6]:
ytd_[symbols].to_excel('market 20200831.xlsx')

In [21]:
vix = yf.download(['^VIX'], start='2010-12-31', end='2020-04-30', thread=True)['Adj Close']

[*********************100%***********************]  1 of 1 completed

In [24]:
vix.to_excel('vix.xlsx')

In [2]:
symbols = ['ACWI', 'ACWX', 'VEU', 'CWI', 'URTH', 'EEM', 'VOO', 'SPY', 'IVV']

In [3]:
df = yf.download(symbols, start='2019-12-31', end='2020-05-31', thread=True)['Adj Close'].iloc[1:]

[*********************100%***********************]  9 of 9 completed

In [8]:
df = df.loc['2020-04-28':'2020-05-28']; df

,ACWI,ACWX,CWI,EEM,IVV,SPY,URTH,VEU,VOO
Date,,,,,,,,,
2020-04-28,68.000000,39.830002,20.678011,36.369999,286.640015,285.730011,85.160004,43.549999,262.679993
2020-04-29,69.800003,40.889999,21.240879,37.430000,294.130005,293.209991,87.410004,44.700001,269.450012
2020-04-30,68.720001,40.049999,20.747135,36.639999,291.160004,290.480011,86.360001,43.810001,267.100006
2020-05-01,66.910004,39.040001,20.233641,35.320000,283.529999,282.790009,84.129997,42.689999,259.820007
2020-05-04,67.129997,39.150002,20.292889,35.700001,284.630005,283.570007,84.300003,42.779999,260.640015
2020-05-05,67.599998,39.279999,20.362015,35.900002,287.140015,286.190002,84.760002,42.970001,263.040009
2020-05-06,67.239998,39.060001,20.233641,35.790001,285.250000,284.250000,84.199997,42.720001,261.269989
2020-05-07,68.129997,39.549999,20.470638,36.080002,288.630005,287.679993,85.309998,43.250000,264.359985
2020-05-08,69.260002,40.220001,20.826134,36.840000,293.459991,292.440002,87.010002,44.000000,268.779999
2020-05-11,69.330002,40.209999,20.806383,36.599998,293.450012,292.500000,87.059998,43.919998,268.820007
2020-05-12,68.160004,39.740002,20.589136,36.459999,287.470001,286.670013,85.430000,43.439999,263.410004
2020-05-13,67.260002,39.439999,20.431139,36.389999,282.540009,281.600006,84.099998,43.139999,258.739990
2020-05-14,67.680000,39.270000,20.332390,36.529999,285.920013,284.970001,84.500000,42.939999,261.859985
2020-05-15,67.739998,39.169998,20.292889,36.029999,287.160004,286.279999,84.870003,42.820000,263.040009
2020-05-18,70.040001,40.680000,21.033506,37.439999,296.040009,295.000000,87.610001,44.480000,271.079987
2020-05-19,69.330002,40.230000,20.796509,37.139999,292.989990,291.970001,86.669998,43.970001,268.519989
2020-05-20,70.489998,40.919998,21.181631,37.630001,297.989990,296.929993,88.260002,44.759998,272.899994
2020-05-21,69.870003,40.509998,20.934759,37.200001,295.809998,294.880005,87.440002,44.250000,270.940002
2020-05-22,69.790001,40.189999,20.727385,36.430000,296.410004,295.440002,87.459999,43.919998,271.549988
2020-05-26,71.099998,41.220001,21.319878,37.230000,300.170013,299.079987,89.089996,45.139999,275.040009
2020-05-27,71.989998,41.650002,21.507502,37.349998,304.549988,303.529999,90.379997,45.540001,279.049988
2020-05-28,72.050003,41.860001,21.625999,37.090000,303.950012,302.970001,90.550003,45.790001,278.500000

In [9]:
(df / df.iloc[0] * [15.27, 6.48, 14.76, 0.98, 6.6, 17.66, 7.26, 10.99, 20]).sum(axis=1)

Date
2020-04-28    100.000000
2020-04-29    102.639250
2020-04-30    101.156192
2020-05-01     98.505312
2020-05-04     98.798316
2020-05-05     99.469361
2020-05-06     98.849112
2020-05-07    100.059136
2020-05-08    101.772261
2020-05-11    101.756386
2020-05-12    100.088323
2020-05-13     98.751216
2020-05-14     99.258452
2020-05-15     99.414611
2020-05-18    102.751473
2020-05-19    101.680320
2020-05-20    103.431250
2020-05-21    102.512783
2020-05-22    102.287282
2020-05-26    104.217611
2020-05-27    105.516705
2020-05-28    105.629203
dtype: float64

In [10]:
df.ACWI/df.ACWI.iloc[0]*100

Date
2020-04-28    100.000000
2020-04-29    102.647063
2020-04-30    101.058825
2020-05-01     98.397064
2020-05-04     98.720584
2020-05-05     99.411762
2020-05-06     98.882350
2020-05-07    100.191172
2020-05-08    101.852944
2020-05-11    101.955885
2020-05-12    100.235300
2020-05-13     98.911768
2020-05-14     99.529412
2020-05-15     99.617644
2020-05-18    103.000001
2020-05-19    101.955885
2020-05-20    103.661762
2020-05-21    102.750004
2020-05-22    102.632354
2020-05-26    104.558821
2020-05-27    105.867644
2020-05-28    105.955887
Name: ACWI, dtype: float64